Linting and Formatting for the backend
utmgdsc/PollVotingSystem pull request #71
Opened 2022-10-10 17:38 UTC by ggggg

#62

2022-10-10 17:39 UTC, ggggg commented
Note: This PR is missing husky integration

2022-10-11 06:55 UTC, hiimchrislim commented
If possible, could you also add in the Husky integration with this? Thanks!

2022-10-11 15:34 UTC, ggggg commented
> If possible, could you also add in the Husky integration with this? Thanks!

No because I cant get it to work on windows, this could be a separate issue.

2022-10-12 05:33 UTC, shubhbapna commented
Husky with github desktop seems to be a known issue with some working hacks

Try:
https://github.com/typicode/husky/issues/1163
https://stackoverflow.com/questions/66520423/github-desktop-husky-pre-commit-hook-does-not

2022-10-12 05:44 UTC, shubhbapna requested changes

2022-10-12 05:44 UTC, shubhbapna commented on server/package.json
> +    "lint": "eslint --ext .ts --fix ."
Add 2 scripts:
- `lint`: no `fix` option
- `lint:fix`: with `fix` passed as option

2022-10-12 06:00 UTC, ggggg commented on server/package.json
> +    "lint": "eslint --ext .ts --fix ."
Done

2022-10-14 01:57 UTC, hiimchrislim commented
What errors are you encountering with Husky on Windows?

2022-10-14 02:47 UTC, ggggg commented
Have a look at https://discord.com/channels/732778344466087967/1025580306926948494/1029134370671427584

2022-10-17 02:49 UTC, shubhbapna approved these changes
LGTM

2022-10-25 03:43 UTC, shubhbapna commented
For next time please try to resolve such issues

You will definitely come across projects where you might not be able to setup your dev environment as smoothly. But it is definitely worth setting up your dev env correctly otherwise your PRs might be blocked until their standards are met.

But congrats on your first PR!

2022-10-25 03:43 UTC, merged